import Head from "next/head";

// component
import { IndexPage } from "../modules/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Discourse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <IndexPage />
      </main>
    </>
  );
}
